AWSTemplateFormatVersion: "2010-09-09"
Description: Template for AWS CodeCommit repository, terraform bucket and lockstate table
Parameters:
  ProjectName:
    Type: String
    Description: Name for CodeCommit repository
    Default: 'bmw-haproxy'
  InitialCommitS3Bucket:
    Type: String
    Description: S3 Bucket with 'zipped' code for initial commit
    Default: 'mm-initial-code-for-codecommit-bucket'

Resources:
  HaproxyRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: HaproxyRepository
      RepositoryName: !Ref ProjectName
      Code:
        S3:
          Properties:
            Bucket: !Ref InitialCommitS3Bucket
  TFSourceS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: !Sub "tf-${AWS::AccountId}-${AWS::Region}-bmw-haproxy"
  TFLockTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
      - AttributeName: LockID
        AttributeType: S
      KeySchema:
      - AttributeName: LockID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Sub "tf-state-lock-${ProjectName}"

Outputs:
  TFS3Bucket:
    Value: !Ref TFSourceS3Bucket
    Export:
      Name: !Sub "stateS3Bucket"
