# Forked from: https://github.com/kentrikos/terraform-aws-shared-proxy-vpc-endpoint
AWSTemplateFormatVersion: '2010-09-09'
Description: "Create CodeBuild project with required IAM/SG/SSM/CW Logs configuration and S3/DynamoDB for Terraform"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label:
        default: "Top-level environment configuration"
      Parameters:
      - NameString
    -
      Label:
        default: "VPC configuration for CodeBuild and VPC Endpoint"
      Parameters:
      - VpcID
      - PrivateSubnetIDs
      - VpcEndpointServiceName
    -
      Label:
        default: "IAM configuration"
      Parameters:
      - IAMCodeBuildPoliciesARNs
    -
      Label:
        default: "Git repository configuration (e.g. Bitbucket)"
      Parameters:
      - ConfigRepoURL
      - ConfigRepoBranch
      - ConfigRepoPath
    -
      Label:
        default: "Terraform tagging"
      Parameters:
      - TerraformTagKey
      - TerraformTagValue


Parameters:
    NameString:
        Description: String that will be used as basis for naming S3 bucket, CB project, etc.
        Type: String
        Default: shared-proxy-vpc-endpoint
    VpcID:
      Type: AWS::EC2::VPC::Id
      Description: VPC in which CB project will run and where VPC Endpoint will be created
    PrivateSubnetIDs:
      Type: List<AWS::EC2::Subnet::Id>
      Description: List of subnets in which CB will run (only private are supported) and where VPC Endpoint will be created
    VpcEndpointServiceName:
      Type: String
      Description: Name of VPC Endpoint Service to which attach VPC Endpoint (formatted as "com.amazonaws.vpce.AWS_REGION.vpce-svc-00000000000000000")
    IAMCodeBuildPoliciesARNs:
      Description: List of IAM policy ARNs to be attached to CodeBuild role (comma separated string, no spaces)
      Default: 'arn:aws:iam::aws:policy/AdministratorAccess'
      Type: String
    ConfigRepoURL:
      Description: Full https URL to configuration repository (starting with https://)
      Type: String
      Default: 'https://github.com/kentrikos/terraform-aws-shared-proxy-vpc-endpoint.git'
    ConfigRepoBranch:
      Description: Name of the git branch or tag to use
      Type: String
      Default: '0.1.1'
    ConfigRepoPath:
      Description: Optional path within the configuration repository (use "." if config files are in root directory)
      Type: String
      Default: 'bootstrap/configuration_repo_template/'
    TerraformTagKey:
      Description: Single tag to be assigned to each resource (that supports tagging) created by Terraform (key)
      Type: String
      Default: 'environment'
    TerraformTagValue:
      Description: Single tag to be assigned to each resource (that supports tagging) created by Terraform (value)
      Type: String
      Default: 'dev'


Resources:
####################################
# PARAMETERS IN SSM PARAMETER STORE:
####################################
  ConfigRepoURLParameterStore:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${NameString}/gitrepo/config_repo_url"
      Type: "String"
      Value: !Ref ConfigRepoURL

  ConfigRepoBranchParameterStore:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${NameString}/gitrepo/config_repo_branch"
      Type: "String"
      Value: !Ref ConfigRepoBranch

  ConfigRepoPathParameterStore:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${NameString}/gitrepo/config_repo_path"
      Type: "String"
      Value: !Ref ConfigRepoPath


####################################
# IAM:
####################################
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        !Split [",", !Ref IAMCodeBuildPoliciesARNs]


####################################
# VPC resources:
####################################
  CodeBuildSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcID
      GroupDescription: CodeBuild SecurityGroup


####################################
# CloudWatch Logs 
####################################
  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup


####################################
# CodeBuild:
####################################
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref NameString
      Description: Run Terraform that deploys NLB/VPC Endpoint Services solution
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        EnvironmentVariables:
        - Name: GIT_CONFIGURATION_REPO_URL
          Value: !Ref ConfigRepoURLParameterStore
          Type: PARAMETER_STORE
        - Name: GIT_CONFIGURATION_REPO_BRANCH
          Value: !Ref ConfigRepoBranchParameterStore
          Type: PARAMETER_STORE
        - Name: GIT_CONFIGURATION_REPO_PATH
          Value: !Ref ConfigRepoPathParameterStore
          Type: PARAMETER_STORE
        - Name: VPC_ID
          Value: !Ref VpcID
          Type: PLAINTEXT
        - Name: PRIVATE_SUBNET_IDS
          Value: !Join [ ",", !Ref PrivateSubnetIDs ]
          Type: PLAINTEXT
        - Name: VPC_ENDPOINT_SERVICE_NAME
          Value: !Ref VpcEndpointServiceName
          Type: PLAINTEXT
        - Name: TERRAFORM_TAG_KEY
          Value: !Ref TerraformTagKey
          Type: PLAINTEXT
        - Name: TERRAFORM_TAG_VALUE
          Value: !Ref TerraformTagValue
          Type: PLAINTEXT
        - Name: TERRAFORM_ACTION
          Value: "create"
          Type: PLAINTEXT
        - Name: TERRAFORM_DELAY_SECONDS
          Value: "10"
          Type: PLAINTEXT
      TimeoutInMinutes: 30
      VpcConfig:
        VpcId: !Ref VpcID
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroup
        Subnets:
          !Ref PrivateSubnetIDs
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref CodeBuildLogGroup
      Source:
        Type: NO_SOURCE
        BuildSpec: !Sub |
          version: 0.2
          env:
            variables:
              TF_STATE_BUCKET: ${TerraformStateBucket}
              TF_LOCK_TABLE: ${TerraformLockTable}
              TF_STATE_BUCKET_KEY: "tf/${NameString}"
              VPC_ID: ${VpcID}
          phases:
            install:
              commands:
                - echo "Installing Terraform"
                - wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
                - unzip terraform_0.11.13_linux_amd64.zip
                - mv terraform /bin
            build:
              commands:
                - env #DEBUG
                - echo "Cloning configuration repository"
                - git clone --branch $GIT_CONFIGURATION_REPO_BRANCH --single-branch $GIT_CONFIGURATION_REPO_URL terraform
                - cd terraform/$GIT_CONFIGURATION_REPO_PATH
                - echo "Generating terraform.tfvars"
                - echo "vpc_id=\"$VPC_ID\"" >> terraform.tfvars
                - export PRIVATE_SUBNET_IDS_CONVERTED="$(echo $PRIVATE_SUBNET_IDS | sed -e 's/^/\"/' -e 's/$/\"/' -e 's/,/\",\"/g')"
                - echo "subnets=[$PRIVATE_SUBNET_IDS_CONVERTED]" >> terraform.tfvars
                - echo "vpc_endpoint_service_name=\"$VPC_ENDPOINT_SERVICE_NAME\"" >> terraform.tfvars
                - echo "common_tag = {key=\"$TERRAFORM_TAG_KEY\", value=\"$TERRAFORM_TAG_VALUE\"}" >> terraform.tfvars
                - echo "region=\"$AWS_REGION\"" >> terraform.tfvars
                - cat terraform.tfvars
                - terraform init -input=false -backend-config=region=$AWS_REGION -backend-config=bucket=$TF_STATE_BUCKET -backend-config=dynamodb_table=$TF_LOCK_TABLE -backend-config=key=$TF_STATE_BUCKET_KEY
                - echo "$TERRAFORM_ACTION" > /tmp/terraform_action # workaround for bash brackets in yaml
                - if grep -q -e "create" -e "plan" /tmp/terraform_action; then terraform plan -out=tfplan -input=false; fi
                - if grep -q "destroy" /tmp/terraform_action; then terraform plan -destroy -out=tfplan -input=false; fi
                - if grep -q "show" /tmp/terraform_action; then terraform show; fi
                - if grep -q -e "create" -e "destroy" /tmp/terraform_action; then sleep $TERRAFORM_DELAY_SECONDS; fi
                - if grep -q -e "create" -e "destroy" /tmp/terraform_action; then terraform apply -input=false tfplan; fi
                - if ! grep -q -e "create" -e "destroy" -e "plan" -e "show" /tmp/terraform_action; then echo "Unsupported TERRAFORM_ACTION, use either create, destroy, plan or show."; fi
####################################
# Terraform state:
####################################
  TerraformStateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: !Sub "tf-${AWS::AccountId}-${AWS::Region}-${NameString}"
      VersioningConfiguration:
        Status: Enabled

  TerraformLockTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
      - AttributeName: LockID
        AttributeType: S
      KeySchema:
      - AttributeName: LockID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Sub "tf-state-lock-${NameString}"


Outputs:
  CodeBuildURL:
    Description: URL to CodeBuild project that will run Terraform
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/codesuite/codebuild/projects/${CodeBuildProject}"